language: cpp
sudo: required
services:
    - docker
dist: trusty
os: linux
env:
    - JOB=cibuild
    - JOB=lint
    - JOB=citest
cache:
  directories:
  - $HOME/.cache/bazel
install: skip
before_script:
    - if [ ! -d "${HOME}/.cache" ]; then mkdir ${HOME}/.cache; fi
    - cp src/BSc2018/apollo-2.0.0/scripts/AGREEMENT.txt ${HOME}/.cache/.apollo_agreement.txt
script:
    - ./src/BSc2018/apollo-2.0.0/docker/scripts/dev_start.sh dev-x86_64-v2.0.0-ci
    - ./src/BSc2018/apollo-2.0.0/apollo_docker.sh ${JOB}
    - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
notifications:
    email:
        on_success: change
        on_failure: always
